info:
  component: Edge Server

server:
  port: 8765

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

proxy:
   auth:
   routes:
   stores: passthru


zuul:
  ignoredServices: "*"
  routes:
    businessunitpath:
      path: /business-units/**
      serviceId: businessunit-service
      stripPrefix: false

      edgepath:
          path: /edge/**
          serviceId: edge-service
          stripPrefix: true

    bediendepath:
      path: /bediendes/**
      serviceId: contract-service
      stripPrefix: false
    contractpath:
      path: /contracts/**
      serviceId: contract-service
      stripPrefix: false
    planningpath:
      path: /planning/**
      serviceId: planning-service
      stripPrefix: true


edge-service:
  token:
    header: Authorization
    secret: flatMap43
    expiration: 604800

logging:
  level:
    ROOT: WARN
    org.springframework.web: WARN
    com.netflix.hystrix: DEBUG
    com.netflix.discovery: FATAL

---
spring:
  profiles: docker
  data:
      mongodb:
        host: edge-mongo

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
