info:
  component: Edge Server

server:
  port: 8765

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    businessunitpath:
      path: /business-units/**
      serviceId: businessunit-service
      stripPrefix: false
    bediendepath:
      path: /bediendes/**
      serviceId: bediende-service
      stripPrefix: false
    contractpath:
      path: /contracts/**
      serviceId: contract-service
      stripPrefix: false

logging:
  level:
    ROOT: WARN
    org.springframework.web: WARN
    com.netflix.hystrix: DEBUG

---
spring:
  profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
